# syntax to create file and folder
- hosts: centos
  tasks:
  - name: Create file on target machine
    file:
      path: /home/ec2-user/sample.txt
      state: touch

  - name: create a dir
    file:
      path: /home/ec2-user/sampledir
      state: directory

  - name: copy file within target VM one location to other
    copy:
      src: /home/ec2-user/hello.txt
      dest: /home/ec2-user/sampledir/hello.txt
      remote_src: yes

  - name: copy file Ansible server to Target VM
    copy:
      src: /home/ec2-user/hello.txt
      dest: /home/ec2-user/ 
